export const SCROLL_INACTIVITY_THRESHOLD_MS = 1000;
export const SCROLL_POINT_GAIN_INTERVAL_MS = 1000;
export const TOTAL_SCROLL_TIME_FOR_POINTS_MS = 60000;
export const POINTS_PER_INTERVAL = 4;
export const MIN_SCROLL_DELTA = 5;
