name: '🚨 이슈 생성'
description: '해야 할 일을 적어주세요.'
title: '[기능명] 제목을 작성해주세요.'
body:
  - type: input
    id: description
    attributes:
      label: '📝 description'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ Tasks'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: false