import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ConditionalLayout from "@/app/_shared/components/ConditionalLayout";

import QueryProvider from "@/app/_shared/providers/QueryProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="h-screen bg-gray-100 flex justify-center overflow-hidden">
            <div className="w-full max-w-[468px] bg-white h-full overflow-y-auto relative">
              <Suspense fallback={null}>
                <ConditionalLayout>{children}</ConditionalLayout>
              </Suspense>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
