import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { QueryProvider } from "@/_shared/providers/QueryProvider";

import "./globals.css";

const pretendard = localFont({
  src: "../../public/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <QueryProvider>
          <div className="h-screen bg-gray-100 flex justify-center overflow-hidden">
            <div className="w-full max-w-[468px] bg-white h-full overflow-y-auto relative">
              <Toaster position="top-center" reverseOrder={false} />
              <Suspense fallback={null}>{children}</Suspense>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
